services:
  mysql-server:
    container_name: mysql-server-statussvc
    image: mysql/mysql-server:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: statussvcdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-server-statussvc:/var/lib/mysql

volumes:
  mysql-server-statussvc:
