# Spring
spring:
  main:
    bannerMode: console
  # Data source
  dataSource:
    url: jdbc:mysql://localhost:3306/${spring.application.name}db
    username: root
    password: Password_23
  jpa:
    showSql: false
  flyway:
    baselineOnMigrate: true
    enabled: true

# Logging
logging:
  config: classpath:log4j2-dev.yml
