# Spring
spring:
  application:
    name: statussvc
  profiles:
    active: default
  main:
    bannerMode: off
  # Data source
  dataSource:
    url: jdbc:mysql://localhost:3306/${spring.application.name}db
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 10
      minimumIdle: 10

  jpa:
    showSql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddlAuto: none
    openInView: false
  # Flyway
  flyway:
    enabled: false
    baselineOnMigrate: false

# Embedded Server
server:
  port: 8080
  serverHeader: ${spring.application.name}
  error:
    includeStackTrace: never
    includeException: false

# Spring Boot Actuator
management:
  endpoints:
    web:
      basePath: /
      exposure:
        include: health, info, flyway

# Application
application:
  service:
    version: 1.0.0

# Logging
logging:
  file:
    name: ${spring.application.name}.log
  config: classpath:log4j2.yml
